[project]
name = "philoagents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "langchain-core>=0.3.75",
    "langchain-groq>=0.3.7",
    "langchain-mongodb>=0.6.2",
    "langgraph>=0.6.6",
    "langgraph-checkpoint-mongodb>=0.1.4",
    "opik>=1.8.36",
    "pre-commit>=4.3.0",
    "pydantic-settings>=2.10.1",
    "pymongo>=4.12.1",
    "langchain-community>=0.3.29",
    "loguru>=0.7.3",
    "langchain-huggingface>=0.3.1",
    "wikipedia>=1.4.0",
    "ipykernel>=6.30.1",
    "pydantic>=2.11.7",
    "datasketch>=1.6.5",
    "sentence-transformers>=5.1.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.11",
]

[tool.pip]
extra-index-url = "https://download.pytorch.org/whl/cpu/torch_stable.html"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/philoagents"]

[tool.ruff]
target-version = "py312"
